// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: vision.proto

package visionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecognizeItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         []byte                 `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeItemRequest) Reset() {
	*x = RecognizeItemRequest{}
	mi := &file_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeItemRequest) ProtoMessage() {}

func (x *RecognizeItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeItemRequest.ProtoReflect.Descriptor instead.
func (*RecognizeItemRequest) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeItemRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *RecognizeItemRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Значения - строки словаря домена ("top", "navy", "winter"); пустое значение - "не знаю".
type RecognizeItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	MainColor     string                 `protobuf:"bytes,3,opt,name=main_color,json=mainColor,proto3" json:"main_color,omitempty"`
	ExtraColors   []string               `protobuf:"bytes,4,rep,name=extra_colors,json=extraColors,proto3" json:"extra_colors,omitempty"`
	Seasons       []string               `protobuf:"bytes,5,rep,name=seasons,proto3" json:"seasons,omitempty"`
	WarmthLevel   int32                  `protobuf:"varint,6,opt,name=warmth_level,json=warmthLevel,proto3" json:"warmth_level,omitempty"`
	Waterproof    bool                   `protobuf:"varint,7,opt,name=waterproof,proto3" json:"waterproof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeItemResponse) Reset() {
	*x = RecognizeItemResponse{}
	mi := &file_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeItemResponse) ProtoMessage() {}

func (x *RecognizeItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeItemResponse.ProtoReflect.Descriptor instead.
func (*RecognizeItemResponse) Descriptor() ([]byte, []int) {
	return file_vision_proto_rawDescGZIP(), []int{1}
}

func (x *RecognizeItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecognizeItemResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RecognizeItemResponse) GetMainColor() string {
	if x != nil {
		return x.MainColor
	}
	return ""
}

func (x *RecognizeItemResponse) GetExtraColors() []string {
	if x != nil {
		return x.ExtraColors
	}
	return nil
}

func (x *RecognizeItemResponse) GetSeasons() []string {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *RecognizeItemResponse) GetWarmthLevel() int32 {
	if x != nil {
		return x.WarmthLevel
	}
	return 0
}

func (x *RecognizeItemResponse) GetWaterproof() bool {
	if x != nil {
		return x.Waterproof
	}
	return false
}

var File_vision_proto protoreflect.FileDescriptor

const file_vision_proto_rawDesc = "" +
	"\n" +
	"\fvision.proto\x12\x11stylist.vision.v1\"O\n" +
	"\x14RecognizeItemRequest\x12\x14\n" +
	"\x05photo\x18\x01 \x01(\fR\x05photo\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xe6\x01\n" +
	"\x15RecognizeItemResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"main_color\x18\x03 \x01(\tR\tmainColor\x12!\n" +
	"\fextra_colors\x18\x04 \x03(\tR\vextraColors\x12\x18\n" +
	"\aseasons\x18\x05 \x03(\tR\aseasons\x12!\n" +
	"\fwarmth_level\x18\x06 \x01(\x05R\vwarmthLevel\x12\x1e\n" +
	"\n" +
	"waterproof\x18\a \x01(\bR\n" +
	"waterproof2p\n" +
	"\n" +
	"Recognizer\x12b\n" +
	"\rRecognizeItem\x12'.stylist.vision.v1.RecognizeItemRequest\x1a(.stylist.vision.v1.RecognizeItemResponseB]Z[github.com/djentelmanick/daily-stylist/backend/internal/adapter/recognizers/vision/visionpbb\x06proto3"

var (
	file_vision_proto_rawDescOnce sync.Once
	file_vision_proto_rawDescData []byte
)

func file_vision_proto_rawDescGZIP() []byte {
	file_vision_proto_rawDescOnce.Do(func() {
		file_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vision_proto_rawDesc), len(file_vision_proto_rawDesc)))
	})
	return file_vision_proto_rawDescData
}

var file_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vision_proto_goTypes = []any{
	(*RecognizeItemRequest)(nil),  // 0: stylist.vision.v1.RecognizeItemRequest
	(*RecognizeItemResponse)(nil), // 1: stylist.vision.v1.RecognizeItemResponse
}
var file_vision_proto_depIdxs = []int32{
	0, // 0: stylist.vision.v1.Recognizer.RecognizeItem:input_type -> stylist.vision.v1.RecognizeItemRequest
	1, // 1: stylist.vision.v1.Recognizer.RecognizeItem:output_type -> stylist.vision.v1.RecognizeItemResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vision_proto_init() }
func file_vision_proto_init() {
	if File_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vision_proto_rawDesc), len(file_vision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vision_proto_goTypes,
		DependencyIndexes: file_vision_proto_depIdxs,
		MessageInfos:      file_vision_proto_msgTypes,
	}.Build()
	File_vision_proto = out.File
	file_vision_proto_goTypes = nil
	file_vision_proto_depIdxs = nil
}
