// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: vision.proto

package visionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Recognizer_RecognizeItem_FullMethodName = "/stylist.vision.v1.Recognizer/RecognizeItem"
)

// RecognizerClient is the client API for Recognizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecognizerClient interface {
	RecognizeItem(ctx context.Context, in *RecognizeItemRequest, opts ...grpc.CallOption) (*RecognizeItemResponse, error)
}

type recognizerClient struct {
	cc grpc.ClientConnInterface
}

func NewRecognizerClient(cc grpc.ClientConnInterface) RecognizerClient {
	return &recognizerClient{cc}
}

func (c *recognizerClient) RecognizeItem(ctx context.Context, in *RecognizeItemRequest, opts ...grpc.CallOption) (*RecognizeItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeItemResponse)
	err := c.cc.Invoke(ctx, Recognizer_RecognizeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecognizerServer is the server API for Recognizer service.
// All implementations must embed UnimplementedRecognizerServer
// for forward compatibility.
type RecognizerServer interface {
	RecognizeItem(context.Context, *RecognizeItemRequest) (*RecognizeItemResponse, error)
	mustEmbedUnimplementedRecognizerServer()
}

// UnimplementedRecognizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecognizerServer struct{}

func (UnimplementedRecognizerServer) RecognizeItem(context.Context, *RecognizeItemRequest) (*RecognizeItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecognizeItem not implemented")
}
func (UnimplementedRecognizerServer) mustEmbedUnimplementedRecognizerServer() {}
func (UnimplementedRecognizerServer) testEmbeddedByValue()                    {}

// UnsafeRecognizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecognizerServer will
// result in compilation errors.
type UnsafeRecognizerServer interface {
	mustEmbedUnimplementedRecognizerServer()
}

func RegisterRecognizerServer(s grpc.ServiceRegistrar, srv RecognizerServer) {
	// If the following call pancis, it indicates UnimplementedRecognizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Recognizer_ServiceDesc, srv)
}

func _Recognizer_RecognizeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServer).RecognizeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recognizer_RecognizeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServer).RecognizeItem(ctx, req.(*RecognizeItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recognizer_ServiceDesc is the grpc.ServiceDesc for Recognizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recognizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stylist.vision.v1.Recognizer",
	HandlerType: (*RecognizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecognizeItem",
			Handler:    _Recognizer_RecognizeItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vision.proto",
}
