// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cities": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Город и настройки"
                ],
                "summary": "Найти город по названию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Часть названия, не короче limits.min_city_query из /api/options",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.citiesResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/cities/at": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Координаты округляются до сотых, около километра: погоде точнее не нужно.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Город и настройки"
                ],
                "summary": "Определить город по координатам",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Широта",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Долгота",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.cityBody"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "404": {
                        "description": "place_not_found",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/city": {
            "put": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Город и настройки"
                ],
                "summary": "Сохранить город пользователя",
                "parameters": [
                    {
                        "description": "Город",
                        "name": "city",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.cityBody"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Город сохранён"
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid_location",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/items": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Гардероб"
                ],
                "summary": "Все вещи пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.itemsResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Гардероб"
                ],
                "summary": "Добавить вещь",
                "parameters": [
                    {
                        "description": "Вещь",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.itemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/miniapp.itemResponse"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "409": {
                        "description": "wardrobe_full",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid_item",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/items/delete": {
            "post": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Не DELETE с телом: тело у DELETE не определено стандартом, и прокси вправе его выбросить.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Гардероб"
                ],
                "summary": "Удалить вещи",
                "parameters": [
                    {
                        "description": "Идентификаторы вещей",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.deleteItemsRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Вещи удалены"
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/items/{id}": {
            "put": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Гардероб"
                ],
                "summary": "Изменить вещь",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор вещи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Вещь",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.itemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.itemResponse"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "404": {
                        "description": "not_found",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid_item",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/items/{id}/status": {
            "put": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Доступна, грязная или в архиве. «Не по сезону» статусом не бывает - это вычисляется по сезонам вещи.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Гардероб"
                ],
                "summary": "Сменить статус вещи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор вещи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.statusRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Статус изменён"
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "404": {
                        "description": "not_found",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid_item",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/options": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Категории, цвета, сезоны, уровни теплоты, статусы и лимиты - с подписями по-русски. Источник значений - домен, поэтому форма не расходится с сервером.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Гардероб"
                ],
                "summary": "Словари для формы вещи",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.optionsResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/outfits/candidates": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Кандидаты отсортированы по тому, насколько вещь подходит: теплота, цвета, дождь, недавнее ношение. Вещи не по сезону уходят в конец списка.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Образ"
                ],
                "summary": "Чем заменить или дополнить образ",
                "parameters": [
                    {
                        "type": "string",
                        "example": "12,15,31",
                        "description": "Идентификаторы вещей образа через запятую",
                        "name": "items",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Какую вещь заменяем. Без неё - добавление вещи в образ",
                        "name": "replace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.candidatesResponse"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "404": {
                        "description": "not_found",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "409": {
                        "description": "location_not_set",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "502": {
                        "description": "weather_unavailable",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/outfits/review": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Те же заметки, что пишет подбор: чего не хватает и что не по погоде.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Образ"
                ],
                "summary": "Разобрать образ по погоде",
                "parameters": [
                    {
                        "type": "string",
                        "example": "12,15,31",
                        "description": "Идентификаторы вещей образа через запятую",
                        "name": "items",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.reviewResponse"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "409": {
                        "description": "location_not_set",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "502": {
                        "description": "weather_unavailable",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/outfits/today": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Только идентификаторы: сами вещи у приложения уже загружены.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Образ"
                ],
                "summary": "Образ дня",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.todayOutfitResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Запись заменяет образ целиком, пустой список его очищает.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Образ"
                ],
                "summary": "Записать образ дня",
                "parameters": [
                    {
                        "description": "Вещи образа",
                        "name": "outfit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.wearRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Образ записан"
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "404": {
                        "description": "not_found",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/photos": {
            "post": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Файл браузер кладёт в хранилище сам, по подписанной ссылке. Размер и тип входят в подпись, ключ придумывает сервер.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Фотографии"
                ],
                "summary": "Запросить ссылку на загрузку фотографии",
                "parameters": [
                    {
                        "description": "Тип и размер файла",
                        "name": "photo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.photoUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/miniapp.photoUploadResponse"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "photo_too_large, photo_type_unsupported",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/photos/recognize": {
            "post": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Пустое поле означает «не знаю»: неверная подсказка хуже её отсутствия.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Фотографии"
                ],
                "summary": "Распознать вещь на загруженной фотографии",
                "parameters": [
                    {
                        "description": "Ключ загруженной фотографии",
                        "name": "photo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.recognizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.suggestionResponse"
                        }
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "photo_not_uploaded",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "429": {
                        "description": "recognition_limit",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "502": {
                        "description": "recognition_unavailable",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/recommendation": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Несколько вариантов, лучший первым. Заметки - готовые строки по-русски.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Образ"
                ],
                "summary": "Подобрать образы на сегодня",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.recommendationResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "409": {
                        "description": "location_not_set",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "502": {
                        "description": "weather_unavailable",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/settings": {
            "get": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "description": "Пока пользователь ничего не менял, возвращаются значения по умолчанию из домена: рассылка включена, время 7:00.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Город и настройки"
                ],
                "summary": "Настройки рассылки и выбранный город",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/miniapp.settingsResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "initData": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Город и настройки"
                ],
                "summary": "Сохранить настройки рассылки",
                "parameters": [
                    {
                        "description": "Настройки",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/miniapp.settingsRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Настройки сохранены"
                    },
                    "400": {
                        "description": "bad_request",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    },
                    "422": {
                        "description": "invalid_settings",
                        "schema": {
                            "$ref": "#/definitions/miniapp.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "miniapp.candidateResponse": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "miniapp.candidatesResponse": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.candidateResponse"
                    }
                }
            }
        },
        "miniapp.categoryOption": {
            "type": "object",
            "properties": {
                "has_warmth": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "miniapp.citiesResponse": {
            "type": "object",
            "properties": {
                "cities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.cityBody"
                    }
                }
            }
        },
        "miniapp.cityBody": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "miniapp.deleteItemsRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "miniapp.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "not_found"
                }
            }
        },
        "miniapp.itemRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "extra_colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "main_color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo_key": {
                    "type": "string"
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "warmth_level": {
                    "type": "integer"
                },
                "waterproof": {
                    "type": "boolean"
                }
            }
        },
        "miniapp.itemResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "extra_colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "main_color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo_key": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "warmth_level": {
                    "type": "integer"
                },
                "waterproof": {
                    "type": "boolean"
                }
            }
        },
        "miniapp.itemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.itemResponse"
                    }
                }
            }
        },
        "miniapp.option": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "miniapp.optionsResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.categoryOption"
                    }
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.option"
                    }
                },
                "current_season": {
                    "type": "string"
                },
                "limits": {
                    "$ref": "#/definitions/miniapp.textLimits"
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.option"
                    }
                },
                "statuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.option"
                    }
                },
                "warmth_levels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.warmthLevelOption"
                    }
                }
            }
        },
        "miniapp.outfitResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.itemResponse"
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "miniapp.photoUploadRequest": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "miniapp.photoUploadResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                },
                "view_url": {
                    "type": "string"
                }
            }
        },
        "miniapp.recognizeRequest": {
            "type": "object",
            "properties": {
                "photo_key": {
                    "type": "string"
                }
            }
        },
        "miniapp.recommendationResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "$ref": "#/definitions/miniapp.cityBody"
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "outfits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/miniapp.outfitResponse"
                    }
                },
                "weather": {
                    "$ref": "#/definitions/miniapp.weatherResponse"
                }
            }
        },
        "miniapp.reviewResponse": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "miniapp.settingsRequest": {
            "type": "object",
            "properties": {
                "morning_enabled": {
                    "type": "boolean"
                },
                "send_at": {
                    "type": "string"
                }
            }
        },
        "miniapp.settingsResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "$ref": "#/definitions/miniapp.cityBody"
                },
                "morning_enabled": {
                    "type": "boolean"
                },
                "send_at": {
                    "type": "string"
                }
            }
        },
        "miniapp.statusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "miniapp.suggestionResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "extra_colors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "main_color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "warmth_level": {
                    "type": "integer"
                },
                "waterproof": {
                    "type": "boolean"
                }
            }
        },
        "miniapp.textLimits": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "integer"
                },
                "min_city_query": {
                    "type": "integer"
                },
                "name": {
                    "type": "integer"
                },
                "photo_bytes": {
                    "type": "integer"
                },
                "photo_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "miniapp.todayOutfitResponse": {
            "type": "object",
            "properties": {
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "miniapp.warmthLevelOption": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "miniapp.wearRequest": {
            "type": "object",
            "properties": {
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "miniapp.weatherResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "temperature": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "initData": {
            "description": "tma \u003cinitData\u003e - данные запуска Mini App, подписанные токеном бота",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.7.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Daily Stylist Mini App API",
	Description:      "API страницы гардероба внутри Telegram. Пользователя сервер узнаёт по подписанным данным запуска Mini App, идентификатор из тела и параметров не берётся.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
